sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"

# command to install dependencies
install:
    - pip install .
    - pip install coveralls flake8

# command to run tests
script:
    - python setup.py nosetests --cover-erase --with-coverage
    - nosetests --with-coverage --cover-min-percentage=100

before_script: flake8 --ignore=W391 statsd tests

after_success:
    - coveralls

