language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.4"
    - "pypy"
    - "pypy3"

# command to install dependencies
install:
    - pip install . --use-mirrors
    - pip install coveralls --use-mirrors

# command to run tests
script:
    - python setup.py nosetests --cover-erase --with-coverage
    - nosetests --with-coverage --cover-min-percentage=100

after_success:
    - coveralls

