language: python
python:
    - "2.6"
    - "2.7"

# command to install dependencies
install:
    - pip install . --use-mirrors
    - pip install coveralls --use-mirrors

# command to run tests
script:
    - python setup.py nosetests

after_success:
    - coveralls

